"""Initial migration

Revision ID: af129ca350c2
Revises: 
Create Date: 2024-08-16 01:15:49.127245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af129ca350c2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('House',
    sa.Column('houseId', sa.UUID(), nullable=False),
    sa.Column('houseName', sa.Text(), nullable=False),
    sa.Column('passwordHash', sa.Text(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('houseId')
    )
    op.create_table('HouseMembers',
    sa.Column('userId', sa.Text(), nullable=False),
    sa.Column('houseId', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['houseId'], ['House.houseId'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('userId', 'houseId')
    )
    op.create_table('Rooms',
    sa.Column('roomId', sa.UUID(), nullable=False),
    sa.Column('roomName', sa.Text(), nullable=True),
    sa.Column('houseId', sa.UUID(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['houseId'], ['House.houseId'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('roomId')
    )
    op.create_table('Devices',
    sa.Column('deviceId', sa.UUID(), nullable=False),
    sa.Column('deviceName', sa.Text(), nullable=False),
    sa.Column('pinNumber', sa.Integer(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('roomId', sa.UUID(), nullable=False),
    sa.Column('isScheduled', sa.Boolean(), nullable=False),
    sa.Column('daysScheduled', sa.VARCHAR(length=30), nullable=True),
    sa.Column('startTime', sa.VARCHAR(length=10), nullable=True),
    sa.Column('offTime', sa.VARCHAR(length=10), nullable=True),
    sa.Column('scheduledBy', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['roomId'], ['Rooms.roomId'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('deviceId')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Devices')
    op.drop_table('Rooms')
    op.drop_table('HouseMembers')
    op.drop_table('House')
    # ### end Alembic commands ###
