"""DeviceControlLogs

Revision ID: f740aca16b1d
Revises: af129ca350c2
Create Date: 2024-08-16 18:22:54.795190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f740aca16b1d'
down_revision: Union[str, None] = 'af129ca350c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('DeviceControlLogs',
    sa.Column('deviceControlLogId', sa.UUID(), nullable=False),
    sa.Column('statusChangedFrom', sa.Boolean(), nullable=False),
    sa.Column('statusChangedTo', sa.Boolean(), nullable=False),
    sa.Column('deviceId', sa.UUID(), nullable=False),
    sa.Column('userId', sa.Text(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('deviceControlLogId')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('DeviceControlLogs')
    # ### end Alembic commands ###
